/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assigment3agui;

/**
 *
 * @author josephbarbosa
 */

public class Assignment3AGUII extends javax.swing.JFrame {

    BankAccountGUI object = new BankAccountGUI();
    
    public Assignment3AGUII() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddressBox = new javax.swing.JTextField();
        SetButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        NameBox = new javax.swing.JTextField();
        SetAddressButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        StateBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CityBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DepositBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MonthsBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RateBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        SetBankInfoButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        CalculateButton = new java.awt.Button();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel1.setText("        $$$$$$$        Welcome to the Bank of El Camino! Please complete the required info below.        $$$$$$$");

        AddressBox.setEnabled(false);
        AddressBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressBoxActionPerformed(evt);
            }
        });

        SetButton.setText("Set");
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel2.setText("Please enter your FULL NAME");

        SetAddressButton.setText("Set");
        SetAddressButton.setEnabled(false);
        SetAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetAddressButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel3.setText("Please enter your ADDRESS");

        StateBox.setEnabled(false);
        StateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel4.setText("State");

        jLabel5.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel5.setText("City");

        CityBox.setEnabled(false);
        CityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityBoxActionPerformed(evt);
            }
        });

        DepositBox.setEnabled(false);
        DepositBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel8.setText("Please enter your DEPOSIT AMOUNT ($)");

        MonthsBox.setEnabled(false);
        MonthsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthsBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel9.setText("Months of Deposit");

        RateBox.setEnabled(false);
        RateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel10.setText("Rate (%)");

        SetBankInfoButton.setText("Set");
        SetBankInfoButton.setEnabled(false);
        SetBankInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetBankInfoButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bangla MN", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        jTextPane1.setDragEnabled(false);
        jScrollPane1.setViewportView(jTextPane1);

        CalculateButton.setLabel("Calculate");
        CalculateButton.setVisible(false);
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Restart ?");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CityBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SetAddressButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel4)))
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(346, 346, 346))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(DepositBox))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MonthsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel9)))
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jLabel10))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(RateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(SetBankInfoButton))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(166, 166, 166)
                                                .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(287, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SetAddressButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MonthsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetBankInfoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(CalculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(499, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
    String address = "";
    String fullName = NameBox.getText();
        if (fullName.equalsIgnoreCase(""))
        {
            jLabel2.setText("Please enter something.");
            fullName = NameBox.getText();
        }
        else
        {
            NameBox.setText(""); 
            object.setUserFullName(fullName);
            jProgressBar1.setValue(10);
            SetButton.setEnabled(false);
            NameBox.setEnabled(false);
            jLabel6.setText("Hello! " + fullName);
            AddressBox.setEnabled(true);
            CityBox.setEnabled(true);
            StateBox.setEnabled(true);
            SetAddressButton.setEnabled(true);
        }
  
    }//GEN-LAST:event_SetButtonActionPerformed

    private void SetAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetAddressButtonActionPerformed
        String address = AddressBox.getText();
        String city = CityBox.getText();
        String state = StateBox.getText();
        
        if (address.equalsIgnoreCase("") || city.equalsIgnoreCase("") || state.equalsIgnoreCase(""))
        {
            if (address.equalsIgnoreCase(""))
            {
                jLabel3.setText("Please enter an address.");
                address = AddressBox.getText();
            }
            if (city.equalsIgnoreCase(""))
            {
                jLabel3.setText("Please enter a city.");
                city = CityBox.getText();
            }
            if (state.equalsIgnoreCase(""))
            {
                jLabel3.setText("Please enter a state.");
                state = StateBox.getText();
            }      
        }
        else
        {
            AddressBox.setText(""); 
            CityBox.setText("");
            StateBox.setText("");
            object.setUserAddress(address);
            object.setUserCity(city);
            object.setUserState(state);
            jProgressBar1.setValue(40);
            AddressBox.setEnabled(false);
            CityBox.setEnabled(false);
            StateBox.setEnabled(false);
            SetAddressButton.setEnabled(false);
            jLabel7.setText(address + " " + city + ", " + state);
            DepositBox.setEnabled(true);
            MonthsBox.setEnabled(true);
            RateBox.setEnabled(true);
            SetBankInfoButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_SetAddressButtonActionPerformed

    private void StateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateBoxActionPerformed

    private void CityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityBoxActionPerformed

    private void AddressBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressBoxActionPerformed

    private void DepositBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepositBoxActionPerformed

    private void MonthsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthsBoxActionPerformed

    private void RateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RateBoxActionPerformed

    private void SetBankInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetBankInfoButtonActionPerformed
        String principalString = "";
        String monthString = "";
        String rateString = "";
        
        double principal;
        int months;
        double rate;
        
        try {
            principalString = DepositBox.getText();
            monthString = MonthsBox.getText();
            rateString = RateBox.getText();
            
            principal = Double.parseDouble(principalString);
            months = Integer.parseInt(monthString);
            rate = (Double.parseDouble(rateString));
            String principalOutput = "";
            principalOutput = principalOutput.format("%.2f", principal); //AFTER PARSING EXCEPTION CHECK
            String monthOutput = Integer.toString(months);
            String rateOutput = Double.toString(rate);
            
            object.setUserPrincipal(principal);
            object.setUserMonths(months);
            object.setUserAnnualRate(rate);
            jLabel11.setText("Deposit: $" + principalOutput + " || Months: " + monthOutput + " || Rate: " + rateOutput + "%");
            SetBankInfoButton.setEnabled(false);
            CalculateButton.setVisible(true);
            jProgressBar1.setValue(80);
            DepositBox.setEnabled(false);
            MonthsBox.setEnabled(false);
            RateBox.setEnabled(false);
            DepositBox.setText("");
            MonthsBox.setText("");
            RateBox.setText("");
            
        }
        catch (NumberFormatException e)
        {
            jLabel11.setText("ERROR! Data NOT SET! Complete ALL fields with NUMERICAL values ONLY.");
            DepositBox.setText("");
            MonthsBox.setText("");
            RateBox.setText("");
        }
        
       
        
        
    }//GEN-LAST:event_SetBankInfoButtonActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        object.calculateUserBonus();
        object.calculateUserInterest();
        object.calculateUserTotal();
        
        String outputLine1 = "";
        outputLine1 = outputLine1.format("\n------------------------------------------------------------------------\n");
        String outputLine2 = "";
        outputLine2 = outputLine2.format("%-30s %s %n" , "Name:", object.getFullName());
        String outputLine3 = "";
        outputLine3 = outputLine3.format("%-30s %s %n" , "Address:", object.getUserAddress());
        String outputLine4 = "";
        outputLine4 = outputLine4.format("%-30s %s %1s %n" , "        ", object.getUserCity(), object.getUserState());
        String outputLine5 = "";
        outputLine5 = outputLine5.format("%-30s %s%.2f %n" , "Deposit:", "$", object.getUserPrincipal());
        String outputLine6 = "";
        outputLine6 = outputLine6.format("%-30s %s%.2f %n" , "Bonus:", "$", object.getUserBonus());
        String outputLine7 = "";
        outputLine7 = outputLine7.format("%-30s %s%.2f %n" , "Interest:", "$", object.getUserInterest());
        String outputLine8 = "";
        outputLine8 = outputLine8.format("%-30s %s%.2f %n" , "Total:", "$", object.getUserTotal());
        String outputLine9 = "";
        outputLine9 = outputLine9.format("------------------------------------------------------------------------\n");
        
        jTextPane1.setText(outputLine1 + outputLine2 + outputLine3 + outputLine4 + outputLine5 + outputLine6 + outputLine7 + outputLine8 + outputLine9);
        jProgressBar1.setValue(100);
        CalculateButton.setVisible(false);
        jButton1.setEnabled(true);
        
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NameBox.setEnabled(true);
        SetButton.setEnabled(true);
        jButton1.setEnabled(false);
        jTextPane1.setText("");
        jLabel11.setVisible(false);
        jProgressBar1.setValue(0);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment3AGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment3AGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment3AGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment3AGUII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment3AGUII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressBox;
    private java.awt.Button CalculateButton;
    private javax.swing.JTextField CityBox;
    private javax.swing.JTextField DepositBox;
    private javax.swing.JTextField MonthsBox;
    private javax.swing.JTextField NameBox;
    private javax.swing.JTextField RateBox;
    private javax.swing.JButton SetAddressButton;
    private javax.swing.JButton SetBankInfoButton;
    private javax.swing.JButton SetButton;
    private javax.swing.JTextField StateBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
