/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalorieCalcGUI;

/**
 *
 * @author josephbarbosa
 */
import java.awt.Font;
public class Assignment1GUI extends javax.swing.JFrame {

    /**
     * Creates new form Assignment1GUI
     */
    
        final int BREAD_CALORIES = 63;
        final int MEAT_CALORIES = 210;
        final int CHEESE_CALORIES = 106;
        final int MAYO_CALORIES = 49;
        final int PICKLE_CALORIES = 25;
        
        int counter = 1;
        
        
        
        
    public Assignment1GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NameConfirmation = new javax.swing.JLabel();
        numBreadComboBox = new javax.swing.JComboBox();
        NumSandwichesLabel = new javax.swing.JLabel();
        NumBreadSlicesLabel = new javax.swing.JLabel();
        numSandwichesComboBox = new javax.swing.JComboBox();
        NumCheeseSlicesLabel = new javax.swing.JLabel();
        NumMayoLabel = new javax.swing.JLabel();
        NumMeatSlicesLabel = new javax.swing.JLabel();
        numMeatComboBox = new javax.swing.JComboBox();
        numCheeseComboBox = new javax.swing.JComboBox();
        numMayoComboBox = new javax.swing.JComboBox();
        NumPicklesLabel = new javax.swing.JLabel();
        numPicklesComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        SolutionBox = new javax.swing.JTextArea();
        CalcCaloriesButton = new javax.swing.JButton();
        NextSandwichButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        SandwichNumberTextField = new javax.swing.JTextPane();
        SandWichOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calorie Counter");

        NameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 12)); // NOI18N
        jLabel1.setText("Name:");

        jButton1.setText("Set Name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NameConfirmation.setForeground(new java.awt.Color(0, 0, 255));

        numBreadComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        numBreadComboBox.setEnabled(false);
        numBreadComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBreadComboBoxActionPerformed(evt);
            }
        });

        NumSandwichesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        NumSandwichesLabel.setText("Please Enter Number Of Sandwiches");
        NumSandwichesLabel.setEnabled(false);

        NumBreadSlicesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        NumBreadSlicesLabel.setText("Bread Slices");

        numSandwichesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        numSandwichesComboBox.setEnabled(false);
        numSandwichesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSandwichesComboBoxActionPerformed(evt);
            }
        });

        NumCheeseSlicesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        NumCheeseSlicesLabel.setText("Cheese Slices");

        NumMayoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        NumMayoLabel.setText("Grams of Mayo");

        NumMeatSlicesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        NumMeatSlicesLabel.setText("Meat Slices");

        numMeatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        numMeatComboBox.setEnabled(false);
        numMeatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMeatComboBoxActionPerformed(evt);
            }
        });

        numCheeseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        numCheeseComboBox.setEnabled(false);
        numCheeseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCheeseComboBoxActionPerformed(evt);
            }
        });

        numMayoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        numMayoComboBox.setEnabled(false);
        numMayoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMayoComboBoxActionPerformed(evt);
            }
        });

        NumPicklesLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        NumPicklesLabel.setText("Pickles Pieces");

        numPicklesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        numPicklesComboBox.setEnabled(false);
        numPicklesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPicklesComboBoxActionPerformed(evt);
            }
        });

        SolutionBox.setColumns(20);
        SolutionBox.setFont(new java.awt.Font("Monospaced", 1, 15)); // NOI18N
        SolutionBox.setRows(5);
        jScrollPane1.setViewportView(SolutionBox);

        CalcCaloriesButton.setText("Calculate Calories");
        CalcCaloriesButton.setEnabled(false);
        CalcCaloriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcCaloriesButtonActionPerformed(evt);
            }
        });

        NextSandwichButton.setText("Next Sandwich");
        NextSandwichButton.setEnabled(false);
        NextSandwichButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextSandwichButtonActionPerformed(evt);
            }
        });

        SandwichNumberTextField.setEnabled(false);
        jScrollPane2.setViewportView(SandwichNumberTextField);

        SandWichOK.setText("OK");
        SandWichOK.setEnabled(false);
        SandWichOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SandWichOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(NumBreadSlicesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numBreadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NumCheeseSlicesLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(NameConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(numCheeseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(NumMeatSlicesLabel)
                        .addGap(33, 33, 33)
                        .addComponent(numMeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(NumPicklesLabel)
                        .addGap(18, 18, 18)
                        .addComponent(numPicklesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NumSandwichesLabel)
                        .addGap(12, 12, 12)
                        .addComponent(numSandwichesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SandWichOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(NumMayoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numMayoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalcCaloriesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextSandwichButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameConfirmation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumSandwichesLabel)
                    .addComponent(numSandwichesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SandWichOK))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numBreadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumMeatSlicesLabel)
                    .addComponent(numMeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumCheeseSlicesLabel)
                    .addComponent(numCheeseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumBreadSlicesLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumPicklesLabel)
                    .addComponent(numPicklesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numMayoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumMayoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CalcCaloriesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextSandwichButton))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NameConfirmation.setText("Hello " + NameBox.getText() + ".");
        NumSandwichesLabel.setEnabled(true);
        numSandwichesComboBox.setEnabled(true);
        SandWichOK.setEnabled(true);
        CalcCaloriesButton.setEnabled(true);
        SandwichNumberTextField.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numBreadComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numBreadComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numBreadComboBoxActionPerformed

    private void numSandwichesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSandwichesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numSandwichesComboBoxActionPerformed

    private void numMeatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMeatComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMeatComboBoxActionPerformed

    private void numCheeseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCheeseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCheeseComboBoxActionPerformed

    private void numMayoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMayoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numMayoComboBoxActionPerformed

    private void numPicklesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPicklesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPicklesComboBoxActionPerformed

    private void CalcCaloriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcCaloriesButtonActionPerformed
             
          
            if (numSandwichesComboBox.getSelectedIndex() == 0)
            {
                SolutionBox.setText("Please indicate how many sandwiches you would want");
            }
            else
            {
             double breadCalories = (numBreadComboBox.getSelectedIndex() * BREAD_CALORIES);
             double meatCalories = (numMeatComboBox.getSelectedIndex() * MEAT_CALORIES);
             double cheeseCalories = (numCheeseComboBox.getSelectedIndex() * CHEESE_CALORIES);
             double mayoCalories = (numMayoComboBox.getSelectedIndex() * MAYO_CALORIES);
             double picklesCalories = (numPicklesComboBox.getSelectedIndex() * PICKLE_CALORIES);
             double totalCalories = (breadCalories + meatCalories + cheeseCalories + mayoCalories + picklesCalories);
           
             
             String bread = String.format("%-30s %20.2f %1s %n", "Bread calories: ", breadCalories, "calories");
             String meat = String.format("%-30s %20.2f %1s %n", "Meat calories: ", meatCalories, "calories");
             String cheese = String.format("%-30s %20.2f %1s %n", "Cheese calories: ", cheeseCalories, "calories");
             String mayo = String.format("%-30s %20.2f %1s %n", "Mayonnaise calories: ", mayoCalories, "calories");
             String pickles = String.format("%-30s %20.2f %1s %n", "Pickles calories: ", picklesCalories, "calories");
             String total = String.format("%-30s %20.2f %1s %n", "Total calories: ", totalCalories, "calories");
             String totalConf = String.format("\n\nThere were %.2f calories in your sandwich\n\n", totalCalories);
            
             
             
             SolutionBox.setText(bread + meat + cheese + mayo + pickles + total + totalConf);
            }
            if (numSandwichesComboBox.getSelectedIndex() > 0)
            {
                NextSandwichButton.setEnabled(true);
            }
             
    }//GEN-LAST:event_CalcCaloriesButtonActionPerformed

    private void SandWichOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SandWichOKActionPerformed
        String numSandwiches = Integer.toString(numSandwichesComboBox.getSelectedIndex());
        if (numSandwichesComboBox.getSelectedIndex() > 0)
        {
            counter = 1;
            SandwichNumberTextField.setText("Sandwich Number " + counter);
        }
        else
        {
            SandwichNumberTextField.setText("Sandwich Number 0");
        }
        
        if (numSandwichesComboBox.getSelectedIndex() > 0)
        {
            SandWichOK.setEnabled(false);
            numSandwichesComboBox.setEnabled(false);
        }
        
        if (numSandwichesComboBox.getSelectedIndex() > 0)
        {
        numBreadComboBox.setEnabled(true);
        numMeatComboBox.setEnabled(true);
        numCheeseComboBox.setEnabled(true);
        numMayoComboBox.setEnabled(true);
        numPicklesComboBox.setEnabled(true);
        }
        
        SolutionBox.setEditable(false);
        SandwichNumberTextField.setEditable(false);
        SolutionBox.setText(null);
    }//GEN-LAST:event_SandWichOKActionPerformed

    private void NextSandwichButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextSandwichButtonActionPerformed
            
            if (numSandwichesComboBox.getSelectedIndex() > 0)
            {
                counter++;
                SandwichNumberTextField.setText("Sandwich Number " + counter);
            }
            if (counter > numSandwichesComboBox.getSelectedIndex())
            {
                SandwichNumberTextField.setVisible(false);
            }
            if (numSandwichesComboBox.getSelectedIndex() == 0)
            {
                SandwichNumberTextField.setText("Sandwich Number: 0");
            }
            
        numBreadComboBox.setSelectedIndex(0);
        numMeatComboBox.setSelectedIndex(0);
        numCheeseComboBox.setSelectedIndex(0);
        numMayoComboBox.setSelectedIndex(0);
        numPicklesComboBox.setSelectedIndex(0);
            
        SolutionBox.setText(null);
        NextSandwichButton.setEnabled(false);
        
            if (counter > numSandwichesComboBox.getSelectedIndex()) 
            {
                SolutionBox.setText("Thank you for using our program!");
                NextSandwichButton.setEnabled(false);
                CalcCaloriesButton.setEnabled(false);
            }
        
            
        
    }//GEN-LAST:event_NextSandwichButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcCaloriesButton;
    private javax.swing.JTextField NameBox;
    private javax.swing.JLabel NameConfirmation;
    private javax.swing.JButton NextSandwichButton;
    private javax.swing.JLabel NumBreadSlicesLabel;
    private javax.swing.JLabel NumCheeseSlicesLabel;
    private javax.swing.JLabel NumMayoLabel;
    private javax.swing.JLabel NumMeatSlicesLabel;
    private javax.swing.JLabel NumPicklesLabel;
    private javax.swing.JLabel NumSandwichesLabel;
    private javax.swing.JButton SandWichOK;
    private javax.swing.JTextPane SandwichNumberTextField;
    private javax.swing.JTextArea SolutionBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox numBreadComboBox;
    private javax.swing.JComboBox numCheeseComboBox;
    private javax.swing.JComboBox numMayoComboBox;
    private javax.swing.JComboBox numMeatComboBox;
    private javax.swing.JComboBox numPicklesComboBox;
    private javax.swing.JComboBox numSandwichesComboBox;
    // End of variables declaration//GEN-END:variables
}
